name: Beta Release

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    tags-ignore:
      - '*'
    branches:
      - main
      - fix-beta-releases

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn install
      - name: Build
        run: yarn build
      - name: Configure committer
        run: |
          git config user.name "Li.Finance"
          git config user.email "<>"
      - name: Create release
        run: yarn release --skip.changelog --prerelease beta
      - name: Publish to npm
        run: npm publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Save changes
        run: git push --follow-tags
